// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import 'dotenv/config';

export default defineConfig({
  schema: './prisma/schema.prisma',
  // TO JEST NOWE ↓↓↓
  datasource: {
    // Prisma wymaga tego przy `prisma migrate deploy`
    url: process.env.DATABASE_URL!,
  },
});	
